WIP

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -159,115 +159,115 @@ jobs:
           echo "e2eFiles=$content" >> $GITHUB_OUTPUT
 
   # based on https://github.com/Synthetixio/synpress/blob/dev/.github/workflows/e2e_cypress-action.yml
-  test-e2e:
-    name: "Test E2E${{ matrix.orbit-test == '1' && ' with L3' || '' }} - ${{ matrix.tests.name }}"
-    runs-on: ubuntu-latest
-    needs: [build, check-files, check-is-hotfix, load-e2e-files]
-    if: needs.check-files.outputs.run_tests == 'true' && needs.check-is-hotfix.outputs.is_hotfix == 'false'
-    strategy:
-      fail-fast: false # If one test fails, let the other tests run
-      matrix:
-        tests:
-          ${{ fromJson(needs.load-e2e-files.outputs.matrix) }}
-        orbit-test: ['0', '1']
+  # test-e2e:
+  #   name: "Test E2E${{ matrix.orbit-test == '1' && ' with L3' || '' }} - ${{ matrix.tests.name }}"
+  #   runs-on: ubuntu-latest
+  #   needs: [build, check-files, check-is-hotfix, load-e2e-files]
+  #   if: needs.check-files.outputs.run_tests == 'true' && needs.check-is-hotfix.outputs.is_hotfix == 'false'
+  #   strategy:
+  #     fail-fast: false # If one test fails, let the other tests run
+  #     matrix:
+  #       tests:
+  #         ${{ fromJson(needs.load-e2e-files.outputs.matrix) }}
+  #       orbit-test: ['0', '1']
 
-    steps:
-      - name: Free Disk Space (Ubuntu)
-        uses: jlumbroso/free-disk-space@main
-        with:
-          # this might remove tools that are actually needed,
-          # if set to "true" but frees about 6 GB
-          tool-cache: false
+  #   steps:
+  #     - name: Free Disk Space (Ubuntu)
+  #       uses: jlumbroso/free-disk-space@main
+  #       with:
+  #         # this might remove tools that are actually needed,
+  #         # if set to "true" but frees about 6 GB
+  #         tool-cache: false
           
-          # all of these default to true, but feel free to set to
-          # "false" if necessary for your workflow
-          android: true
-          dotnet: true
-          haskell: true
-          large-packages: true
-          docker-images: false
-          swap-storage: true
+  #         # all of these default to true, but feel free to set to
+  #         # "false" if necessary for your workflow
+  #         android: true
+  #         dotnet: true
+  #         haskell: true
+  #         large-packages: true
+  #         docker-images: false
+  #         swap-storage: true
 
-      - name: Checkout
-        uses: actions/checkout@v4
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Install node_modules
-        uses: OffchainLabs/actions/node-modules/install@main
+  #     - name: Install node_modules
+  #       uses: OffchainLabs/actions/node-modules/install@main
 
-      - name: Restore build artifacts
-        uses: ./.github/actions/build-artifacts/restore
+  #     - name: Restore build artifacts
+  #       uses: ./.github/actions/build-artifacts/restore
 
-      - name: Install cypress
-        run: yarn cypress install
+  #     - name: Install cypress
+  #       run: yarn cypress install
 
-      - name: Install linux dependencies
-        run: |
-          sudo apt-get install --no-install-recommends -y \
-          fluxbox \
-          xvfb
+  #     - name: Install linux dependencies
+  #       run: |
+  #         sudo apt-get install --no-install-recommends -y \
+  #         fluxbox \
+  #         xvfb
 
-      - name: Run xvfb and fluxbox
-        run: |
-          Xvfb :0 -screen 0 1366x768x24 -listen tcp -ac &
-          fluxbox &
-        env:
-          DISPLAY: :0.0
+  #     - name: Run xvfb and fluxbox
+  #       run: |
+  #         Xvfb :0 -screen 0 1366x768x24 -listen tcp -ac &
+  #         fluxbox &
+  #       env:
+  #         DISPLAY: :0.0
 
-      - name: Run nitro testnode
-        uses: OffchainLabs/actions/run-nitro-test-node@a20a76172ce524832ac897bef2fa10a62ed81c29
-        with:
-          nitro-testnode-ref: aab133aceadec2e622f15fa438f6327e3165392d
-          l3-node: ${{ matrix.orbit-test == '1' }}
-          no-l3-token-bridge: ${{ matrix.orbit-test == '0' }}
+  #     - name: Run nitro testnode
+  #       uses: OffchainLabs/actions/run-nitro-test-node@a20a76172ce524832ac897bef2fa10a62ed81c29
+  #       with:
+  #         nitro-testnode-ref: aab133aceadec2e622f15fa438f6327e3165392d
+  #         l3-node: ${{ matrix.orbit-test == '1' }}
+  #         no-l3-token-bridge: ${{ matrix.orbit-test == '0' }}
 
-      - name: Run e2e tests via cypress-io/github-action
-        uses: cypress-io/github-action@8d3918616d8ac34caa2b49afc8b408b6a872a6f5 # pin@v6.7.1
-        with:
-          start: yarn start
-          command: ${{ matrix.orbit-test == '1' && 'yarn test:e2e:orbit --browser chromium' || 'yarn test:e2e --browser chromium' }}
-          wait-on: http://127.0.0.1:3000
-          wait-on-timeout: 120
-          spec: ./packages/arb-token-bridge-ui/tests/e2e/specs/*
-        env:
-          DISPLAY: :0.0
-          TEST_FILE: ${{ matrix.tests.file }}
-          SKIP_METAMASK_SETUP: true
-          CYPRESS_RECORD_VIDEO: ${{ matrix.tests.recordVideo }}
-          PRIVATE_KEY_CUSTOM: ${{ secrets.E2E_PRIVATE_KEY }}
-          PRIVATE_KEY_USER: ${{ secrets.E2E_PRIVATE_KEY_USER }}
-          NEXT_PUBLIC_IS_E2E_TEST: true
-          NEXT_PUBLIC_INFURA_KEY: ${{ secrets.NEXT_PUBLIC_INFURA_KEY }}
-          NEXT_PUBLIC_LOCAL_ETHEREUM_RPC_URL: http://127.0.0.1:8545
-          NEXT_PUBLIC_LOCAL_ARBITRUM_RPC_URL: http://127.0.0.1:8547
-          NEXT_PUBLIC_LOCAL_L3_RPC_URL: http://127.0.0.1:3347
+  #     - name: Run e2e tests via cypress-io/github-action
+  #       uses: cypress-io/github-action@8d3918616d8ac34caa2b49afc8b408b6a872a6f5 # pin@v6.7.1
+  #       with:
+  #         start: yarn start
+  #         command: ${{ matrix.orbit-test == '1' && 'yarn test:e2e:orbit --browser chromium' || 'yarn test:e2e --browser chromium' }}
+  #         wait-on: http://127.0.0.1:3000
+  #         wait-on-timeout: 120
+  #         spec: ./packages/arb-token-bridge-ui/tests/e2e/specs/*
+  #       env:
+  #         DISPLAY: :0.0
+  #         TEST_FILE: ${{ matrix.tests.file }}
+  #         SKIP_METAMASK_SETUP: true
+  #         CYPRESS_RECORD_VIDEO: ${{ matrix.tests.recordVideo }}
+  #         PRIVATE_KEY_CUSTOM: ${{ secrets.E2E_PRIVATE_KEY }}
+  #         PRIVATE_KEY_USER: ${{ secrets.E2E_PRIVATE_KEY_USER }}
+  #         NEXT_PUBLIC_IS_E2E_TEST: true
+  #         NEXT_PUBLIC_INFURA_KEY: ${{ secrets.NEXT_PUBLIC_INFURA_KEY }}
+  #         NEXT_PUBLIC_LOCAL_ETHEREUM_RPC_URL: http://127.0.0.1:8545
+  #         NEXT_PUBLIC_LOCAL_ARBITRUM_RPC_URL: http://127.0.0.1:8547
+  #         NEXT_PUBLIC_LOCAL_L3_RPC_URL: http://127.0.0.1:3347
 
-      - name: Archive e2e artifacts
-        uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: e2e-artifacts-pull-request-${{ github.event.pull_request.number }}-commit-${{ github.sha }}
-          path: |
-            ./packages/arb-token-bridge-ui/cypress/videos
-            ./packages/arb-token-bridge-ui/cypress/screenshots
-        continue-on-error: true
+  #     - name: Archive e2e artifacts
+  #       uses: actions/upload-artifact@v4
+  #       if: always()
+  #       with:
+  #         name: e2e-artifacts-pull-request-${{ github.event.pull_request.number }}-commit-${{ github.sha }}
+  #         path: |
+  #           ./packages/arb-token-bridge-ui/cypress/videos
+  #           ./packages/arb-token-bridge-ui/cypress/screenshots
+  #       continue-on-error: true
 
-      - name: Throw error if tests failed
-        if: steps.e2e-run.outputs.status == 'failed'
-        run: exit 1
+  #     - name: Throw error if tests failed
+  #       if: steps.e2e-run.outputs.status == 'failed'
+  #       run: exit 1
 
-  test-e2e-success:
-    name: "Test E2E Success"
-    runs-on: ubuntu-latest
-    needs: [test-e2e]
-    if: always()
-    steps:
-      - name: E2E Succeeded
-        if: needs.test-e2e.result == 'success' || needs.test-e2e.result == 'skipped'
-        run: echo "nice"
+  # test-e2e-success:
+  #   name: "Test E2E Success"
+  #   runs-on: ubuntu-latest
+  #   needs: [test-e2e]
+  #   if: always()
+  #   steps:
+  #     - name: E2E Succeeded
+  #       if: needs.test-e2e.result == 'success' || needs.test-e2e.result == 'skipped'
+  #       run: echo "nice"
 
-      - name: E2E Failed
-        if: needs.test-e2e.result != 'success' && needs.test-e2e.result != 'skipped'
-        run: exit 1
+  #     - name: E2E Failed
+  #       if: needs.test-e2e.result != 'success' && needs.test-e2e.result != 'skipped'
+  #       run: exit 1
 
   load-e2e-cctp-files:
     name: "Load e2e CCTP files"
