Cleanup

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -372,18 +372,18 @@ jobs:
   #       run: exit 1
 
   # test-e2e-cctp-success:
-    name: "Test E2E CCTP Success"
-    runs-on: ubuntu-latest
-    needs: [test-e2e-cctp]
-    if: always()
-    steps:
-      - name: E2E Succeeded
-        if: needs.test-e2e-cctp.result == 'success' || needs.test-e2e-cctp.result == 'skipped'
-        run: echo "nice"
+  #   name: "Test E2E CCTP Success"
+  #   runs-on: ubuntu-latest
+  #   needs: [test-e2e-cctp]
+  #   if: always()
+  #   steps:
+  #     - name: E2E Succeeded
+  #       if: needs.test-e2e-cctp.result == 'success' || needs.test-e2e-cctp.result == 'skipped'
+  #       run: echo "nice"
 
-      - name: E2E Failed
-        if: needs.test-e2e-cctp.result != 'success' && needs.test-e2e-cctp.result != 'skipped'
-        run: exit 1
+  #     - name: E2E Failed
+  #       if: needs.test-e2e-cctp.result != 'success' && needs.test-e2e-cctp.result != 'skipped'
+  #       run: exit 1
 
   clean-up:
     name: "Clean Up"
